#spring.application.name=cards

#server.port=9091

# MYSQL properties
#spring.datasource.url=jdbc:mysql://localhost:3306/cards
#spring.datasource.username=root
#spring.datasource.password=anish123

#JPA Properies
#spring.jpa.properties.hibernate.dialect=org.hibermate.dialect.MySQLDialect 
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


server:
  port: 9091
  
spring:
 application:
  name: cards
 profiles:
  active: "prod"
 datasource:
  url: jdbc:mysql://localhost:3306/cards
  username: anish
  password: anish123
 jpa:
  properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
   ddl-auto: update
  show-sql: true
  
 config:
  import: "optional:configserver:http://localhost:8071/"

management:
 endpoints:
  web:
   exposure:
    include: "*"




