
services:
 configserver:
  image: "slvranish/configserver:s8"
  container_name: configserver-ms
  ports:
   - "8071:8071" 
  healthcheck:
   test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
   interval: 10s
   timeout: 5s
   retries: 10
   start_period: 10s
  extends:
   file: common-config.yml
   service: microservice-base-config

 eurekaserver:
  image: "slvranish/eurekaserver:s8"
  container_name: eurekaserver-ms
  ports:
   - "8070:8070" 
  healthcheck:
   test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
   interval: 10s
   timeout: 5s
   retries: 10
   start_period: 10s
  extends:
   file: common-config.yml
   service: microservice-base-config   
  depends_on:
   configserver:
    condition: service_healthy

  environment:
   SPRING_APPLICATION_NAME: "eurekaserver"
  
 accounts:
  image: "slvranish/accounts:s8"
  container_name: accounts-ms
  ports:
   - "9090:9090"
  #depends_on:
   #configserver:
    #condition: service_healthy
   #eurekaserver:
    #condition: service_healthy
  environment:
   SPRING_APPLICATION_NAME: "accounts"
  extends:
   file: common-config.yml
   service: microservice-configserver-config
  

 loans:
  image: "slvranish/loans:s8"
  container_name: loans-ms
  ports:
   - "9092:9092"
  #depends_on:
   #configserver:
    #condition: service_healthy
   #eurekaserver:
    #condition: service_healthy
  environment:
   SPRING_APPLICATION_NAME: "loans"
  extends:
   file: common-config.yml
   service: microservice-configserver-config
     

 cards:
  image: "slvranish/cards:s8"
  container_name: cards-ms
  ports:
   - "9091:9091"
 # depends_on:
  # configserver:
   # condition: service_healthy
   #urekaserver:
    #condition: service_healthy
  environment:
   SPRING_APPLICATION_NAME: "cards"
  extends:
   file: common-config.yml
   service: microservice-configserver-config
     


networks:
 risrchanish:
  driver: "bridge"	