#spring.application.name=accounts

#server.port=9090

# MySQL properties
#spring.datasource.url=jdbc:mysql://localhost:3306/accounts
#spring.datasource.username=anish
#spring.datasource.password=anish123

# JPA Properties
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


server:
  port: 9090
  
spring:
 application:
  name: "accounts"
 profiles:
  active: "prod"
 datasource:
  url: jdbc:mysql://localhost:3306/accounts
  username: anish
  password: anish123
 jpa:
  properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
   ddl-auto: update
  show-sql: true

 config:
  import: "optional:configserver:http://localhost:8071/"


management:
 endpoints:
  web:
   exposure:
    include: "*"

